# Generated by Django 2.0.5 on 2018-05-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
